[package]
name = "string-inspector"
version = "0.0.1"
authors = ["Mat Moore <matmoore@users.noreply.github.com>"]
edition = "2018"

[dependencies]
colored = "1.8"
terminal_size = "0.1.8"
encoding = "0.2"